version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "hfhbd"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "hfhbd"
  - package-ecosystem: "devcontainer"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "hfhbd"
